// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: model/http.proto

package model

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAccessTokenRequest) Reset() {
	*x = RefreshAccessTokenRequest{}
	mi := &file_model_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenRequest) ProtoMessage() {}

func (x *RefreshAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshAccessTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshAccessTokenResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string     `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessTokenExpireTime *Timestamp `protobuf:"bytes,2,opt,name=accessTokenExpireTime,proto3" json:"accessTokenExpireTime,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RefreshAccessTokenResponse) Reset() {
	*x = RefreshAccessTokenResponse{}
	mi := &file_model_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenResponse) ProtoMessage() {}

func (x *RefreshAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshAccessTokenResponse) GetAccessTokenExpireTime() *Timestamp {
	if x != nil {
		return x.AccessTokenExpireTime
	}
	return nil
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int64                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_model_http_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{2}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int64 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type ListChatRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPageSize   int64                  `protobuf:"varint,1,opt,name=max_page_size,json=maxPageSize,proto3" json:"max_page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatRoomsRequest) Reset() {
	*x = ListChatRoomsRequest{}
	mi := &file_model_http_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatRoomsRequest) ProtoMessage() {}

func (x *ListChatRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListChatRoomsRequest) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{3}
}

func (x *ListChatRoomsRequest) GetMaxPageSize() int64 {
	if x != nil {
		return x.MaxPageSize
	}
	return 0
}

type ChatRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatRoomId    string                 `protobuf:"bytes,2,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	UserProfile   *UserProfile           `protobuf:"bytes,3,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"` // 其他的用不上
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoom) Reset() {
	*x = ChatRoom{}
	mi := &file_model_http_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoom) ProtoMessage() {}

func (x *ChatRoom) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoom.ProtoReflect.Descriptor instead.
func (*ChatRoom) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRoom) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRoom) GetChatRoomId() string {
	if x != nil {
		return x.ChatRoomId
	}
	return ""
}

func (x *ChatRoom) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

type ListChatRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatRooms     []*ChatRoom            `protobuf:"bytes,1,rep,name=chat_rooms,json=chatRooms,proto3" json:"chat_rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatRoomsResponse) Reset() {
	*x = ListChatRoomsResponse{}
	mi := &file_model_http_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatRoomsResponse) ProtoMessage() {}

func (x *ListChatRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListChatRoomsResponse) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{5}
}

func (x *ListChatRoomsResponse) GetChatRooms() []*ChatRoom {
	if x != nil {
		return x.ChatRooms
	}
	return nil
}

type ListChatMessagesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatRoomId          string                 `protobuf:"bytes,2,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	MaxPageSize         int32                  `protobuf:"varint,3,opt,name=max_page_size,json=maxPageSize,proto3" json:"max_page_size,omitempty"`
	CursorChatMessageId string                 `protobuf:"bytes,4,opt,name=cursor_chat_message_id,json=cursorChatMessageId,proto3" json:"cursor_chat_message_id,omitempty"`
	Backward            bool                   `protobuf:"varint,5,opt,name=backward,proto3" json:"backward,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListChatMessagesRequest) Reset() {
	*x = ListChatMessagesRequest{}
	mi := &file_model_http_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessagesRequest) ProtoMessage() {}

func (x *ListChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{6}
}

func (x *ListChatMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListChatMessagesRequest) GetChatRoomId() string {
	if x != nil {
		return x.ChatRoomId
	}
	return ""
}

func (x *ListChatMessagesRequest) GetMaxPageSize() int32 {
	if x != nil {
		return x.MaxPageSize
	}
	return 0
}

func (x *ListChatMessagesRequest) GetCursorChatMessageId() string {
	if x != nil {
		return x.CursorChatMessageId
	}
	return ""
}

func (x *ListChatMessagesRequest) GetBackward() bool {
	if x != nil {
		return x.Backward
	}
	return false
}

type ListChatMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatRoomId    string                 `protobuf:"bytes,2,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	ChatMessageId string       `protobuf:"bytes,3,opt,name=chat_message_id,json=chatMessageId,proto3" json:"chat_message_id,omitempty"`
	UserProfile   *UserProfile `protobuf:"bytes,4,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	Type          int32        `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	VideoUrl      string       `protobuf:"bytes,8,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Timestamp     *Timestamp   `protobuf:"bytes,100,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TimeStr       string       `protobuf:"bytes,200,opt,name=time_str,json=timeStr,proto3" json:"time_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMessages) Reset() {
	*x = ListChatMessages{}
	mi := &file_model_http_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessages) ProtoMessage() {}

func (x *ListChatMessages) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessages.ProtoReflect.Descriptor instead.
func (*ListChatMessages) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatMessages) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListChatMessages) GetChatRoomId() string {
	if x != nil {
		return x.ChatRoomId
	}
	return ""
}

func (x *ListChatMessages) GetChatMessageId() string {
	if x != nil {
		return x.ChatMessageId
	}
	return ""
}

func (x *ListChatMessages) GetUserProfile() *UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

func (x *ListChatMessages) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListChatMessages) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ListChatMessages) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ListChatMessages) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *ListChatMessages) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ListChatMessages) GetTimeStr() string {
	if x != nil {
		return x.TimeStr
	}
	return ""
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UniqueId      string                 `protobuf:"bytes,2,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_model_http_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{8}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type ListChatMessagesResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Messages                []*ListChatMessages    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageCursorMessageId string                 `protobuf:"bytes,4,opt,name=next_page_cursor_message_id,json=nextPageCursorMessageId,proto3" json:"next_page_cursor_message_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListChatMessagesResponse) Reset() {
	*x = ListChatMessagesResponse{}
	mi := &file_model_http_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessagesResponse) ProtoMessage() {}

func (x *ListChatMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListChatMessagesResponse) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{9}
}

func (x *ListChatMessagesResponse) GetMessages() []*ListChatMessages {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListChatMessagesResponse) GetNextPageCursorMessageId() string {
	if x != nil {
		return x.NextPageCursorMessageId
	}
	return ""
}

type GetChatRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatRoomId    string                 `protobuf:"bytes,2,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRoomRequest) Reset() {
	*x = GetChatRoomRequest{}
	mi := &file_model_http_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRoomRequest) ProtoMessage() {}

func (x *GetChatRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRoomRequest.ProtoReflect.Descriptor instead.
func (*GetChatRoomRequest) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{10}
}

func (x *GetChatRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetChatRoomRequest) GetChatRoomId() string {
	if x != nil {
		return x.ChatRoomId
	}
	return ""
}

type CheckStreamLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStreamLiveRequest) Reset() {
	*x = CheckStreamLiveRequest{}
	mi := &file_model_http_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStreamLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStreamLiveRequest) ProtoMessage() {}

func (x *CheckStreamLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStreamLiveRequest.ProtoReflect.Descriptor instead.
func (*CheckStreamLiveRequest) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{11}
}

type CheckStreamLiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int32                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2        int32         `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	LiveInfo      []*LiveStream `protobuf:"bytes,3,rep,name=live_info,json=liveInfo,proto3" json:"live_info,omitempty"`
	UserProfile   []*LiveUser   `protobuf:"bytes,4,rep,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStreamLiveResponse) Reset() {
	*x = CheckStreamLiveResponse{}
	mi := &file_model_http_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStreamLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStreamLiveResponse) ProtoMessage() {}

func (x *CheckStreamLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStreamLiveResponse.ProtoReflect.Descriptor instead.
func (*CheckStreamLiveResponse) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{12}
}

func (x *CheckStreamLiveResponse) GetField1() int32 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *CheckStreamLiveResponse) GetField2() int32 {
	if x != nil {
		return x.Field2
	}
	return 0
}

func (x *CheckStreamLiveResponse) GetLiveInfo() []*LiveStream {
	if x != nil {
		return x.LiveInfo
	}
	return nil
}

func (x *CheckStreamLiveResponse) GetUserProfile() []*LiveUser {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

type LiveStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LiveId        string                 `protobuf:"bytes,1,opt,name=live_id,json=liveId,proto3" json:"live_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StreamStatus  int32                  `protobuf:"varint,3,opt,name=stream_status,json=streamStatus,proto3" json:"stream_status,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	WebrtcUrl     string                 `protobuf:"bytes,13,opt,name=webrtc_url,json=webrtcUrl,proto3" json:"webrtc_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveStream) Reset() {
	*x = LiveStream{}
	mi := &file_model_http_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStream) ProtoMessage() {}

func (x *LiveStream) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStream.ProtoReflect.Descriptor instead.
func (*LiveStream) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{13}
}

func (x *LiveStream) GetLiveId() string {
	if x != nil {
		return x.LiveId
	}
	return ""
}

func (x *LiveStream) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LiveStream) GetStreamStatus() int32 {
	if x != nil {
		return x.StreamStatus
	}
	return 0
}

func (x *LiveStream) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LiveStream) GetWebrtcUrl() string {
	if x != nil {
		return x.WebrtcUrl
	}
	return ""
}

type LiveUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Info          *UserProfile `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveUser) Reset() {
	*x = LiveUser{}
	mi := &file_model_http_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveUser) ProtoMessage() {}

func (x *LiveUser) ProtoReflect() protoreflect.Message {
	mi := &file_model_http_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveUser.ProtoReflect.Descriptor instead.
func (*LiveUser) Descriptor() ([]byte, []int) {
	return file_model_http_proto_rawDescGZIP(), []int{14}
}

func (x *LiveUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LiveUser) GetInfo() *UserProfile {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_model_http_proto protoreflect.FileDescriptor

const file_model_http_proto_rawDesc = "" +
	"\n" +
	"\x10model/http.proto\x12\x05model\"@\n" +
	"\x19RefreshAccessTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x86\x01\n" +
	"\x1aRefreshAccessTokenResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12F\n" +
	"\x15accessTokenExpireTime\x18\x02 \x01(\v2\x10.model.TimestampR\x15accessTokenExpireTime\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x03R\x05nanos\":\n" +
	"\x14ListChatRoomsRequest\x12\"\n" +
	"\rmax_page_size\x18\x01 \x01(\x03R\vmaxPageSize\"|\n" +
	"\bChatRoom\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\fchat_room_id\x18\x02 \x01(\tR\n" +
	"chatRoomId\x125\n" +
	"\fuser_profile\x18\x03 \x01(\v2\x12.model.UserProfileR\vuserProfile\"G\n" +
	"\x15ListChatRoomsResponse\x12.\n" +
	"\n" +
	"chat_rooms\x18\x01 \x03(\v2\x0f.model.ChatRoomR\tchatRooms\"\xc9\x01\n" +
	"\x17ListChatMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\fchat_room_id\x18\x02 \x01(\tR\n" +
	"chatRoomId\x12\"\n" +
	"\rmax_page_size\x18\x03 \x01(\x05R\vmaxPageSize\x123\n" +
	"\x16cursor_chat_message_id\x18\x04 \x01(\tR\x13cursorChatMessageId\x12\x1a\n" +
	"\bbackward\x18\x05 \x01(\bR\bbackward\"\xe0\x02\n" +
	"\x10ListChatMessages\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\fchat_room_id\x18\x02 \x01(\tR\n" +
	"chatRoomId\x12&\n" +
	"\x0fchat_message_id\x18\x03 \x01(\tR\rchatMessageId\x125\n" +
	"\fuser_profile\x18\x04 \x01(\v2\x12.model.UserProfileR\vuserProfile\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tvideo_url\x18\b \x01(\tR\bvideoUrl\x12.\n" +
	"\ttimestamp\x18d \x01(\v2\x10.model.TimestampR\ttimestamp\x12\x1a\n" +
	"\btime_str\x18\xc8\x01 \x01(\tR\atimeStr\"\x85\x01\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tunique_id\x18\x02 \x01(\tR\buniqueId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"\x8d\x01\n" +
	"\x18ListChatMessagesResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.model.ListChatMessagesR\bmessages\x12<\n" +
	"\x1bnext_page_cursor_message_id\x18\x04 \x01(\tR\x17nextPageCursorMessageId\"O\n" +
	"\x12GetChatRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\fchat_room_id\x18\x02 \x01(\tR\n" +
	"chatRoomId\"\x18\n" +
	"\x16CheckStreamLiveRequest\"\xad\x01\n" +
	"\x17CheckStreamLiveResponse\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x05R\x06field1\x12\x16\n" +
	"\x06field2\x18\x02 \x01(\x05R\x06field2\x12.\n" +
	"\tlive_info\x18\x03 \x03(\v2\x11.model.LiveStreamR\bliveInfo\x122\n" +
	"\fuser_profile\x18\x04 \x03(\v2\x0f.model.LiveUserR\vuserProfile\"\x98\x01\n" +
	"\n" +
	"LiveStream\x12\x17\n" +
	"\alive_id\x18\x01 \x01(\tR\x06liveId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rstream_status\x18\x03 \x01(\x05R\fstreamStatus\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"webrtc_url\x18\r \x01(\tR\twebrtcUrl\"B\n" +
	"\bLiveUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04info\x18\x02 \x01(\v2\x12.model.UserProfileR\x04infoB\tZ\a./modelb\x06proto3"

var (
	file_model_http_proto_rawDescOnce sync.Once
	file_model_http_proto_rawDescData []byte
)

func file_model_http_proto_rawDescGZIP() []byte {
	file_model_http_proto_rawDescOnce.Do(func() {
		file_model_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_http_proto_rawDesc), len(file_model_http_proto_rawDesc)))
	})
	return file_model_http_proto_rawDescData
}

var file_model_http_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_model_http_proto_goTypes = []any{
	(*RefreshAccessTokenRequest)(nil),  // 0: model.RefreshAccessTokenRequest
	(*RefreshAccessTokenResponse)(nil), // 1: model.RefreshAccessTokenResponse
	(*Timestamp)(nil),                  // 2: model.Timestamp
	(*ListChatRoomsRequest)(nil),       // 3: model.ListChatRoomsRequest
	(*ChatRoom)(nil),                   // 4: model.ChatRoom
	(*ListChatRoomsResponse)(nil),      // 5: model.ListChatRoomsResponse
	(*ListChatMessagesRequest)(nil),    // 6: model.ListChatMessagesRequest
	(*ListChatMessages)(nil),           // 7: model.ListChatMessages
	(*UserProfile)(nil),                // 8: model.UserProfile
	(*ListChatMessagesResponse)(nil),   // 9: model.ListChatMessagesResponse
	(*GetChatRoomRequest)(nil),         // 10: model.GetChatRoomRequest
	(*CheckStreamLiveRequest)(nil),     // 11: model.CheckStreamLiveRequest
	(*CheckStreamLiveResponse)(nil),    // 12: model.CheckStreamLiveResponse
	(*LiveStream)(nil),                 // 13: model.LiveStream
	(*LiveUser)(nil),                   // 14: model.LiveUser
}
var file_model_http_proto_depIdxs = []int32{
	2,  // 0: model.RefreshAccessTokenResponse.accessTokenExpireTime:type_name -> model.Timestamp
	8,  // 1: model.ChatRoom.user_profile:type_name -> model.UserProfile
	4,  // 2: model.ListChatRoomsResponse.chat_rooms:type_name -> model.ChatRoom
	8,  // 3: model.ListChatMessages.user_profile:type_name -> model.UserProfile
	2,  // 4: model.ListChatMessages.timestamp:type_name -> model.Timestamp
	7,  // 5: model.ListChatMessagesResponse.messages:type_name -> model.ListChatMessages
	13, // 6: model.CheckStreamLiveResponse.live_info:type_name -> model.LiveStream
	14, // 7: model.CheckStreamLiveResponse.user_profile:type_name -> model.LiveUser
	8,  // 8: model.LiveUser.info:type_name -> model.UserProfile
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_model_http_proto_init() }
func file_model_http_proto_init() {
	if File_model_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_http_proto_rawDesc), len(file_model_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_http_proto_goTypes,
		DependencyIndexes: file_model_http_proto_depIdxs,
		MessageInfos:      file_model_http_proto_msgTypes,
	}.Build()
	File_model_http_proto = out.File
	file_model_http_proto_goTypes = nil
	file_model_http_proto_depIdxs = nil
}
