proxy:
  host: "127.0.0.1"
  port: 7890
refresh_token: ""
ffmpeg_path: ""  # C:/ffmpeg/bin/ffmpeg.exe
media_path_win: ""
media_path_linux: ""
email:
  smtp_host: "smtp.qq.com"
  sender: "xxxx@qq.com"
  auth_code: ""
  receiver: "xxx@163.com"
